[project]
name = "gantty"
version = "1.1.0"
description = "Gantt diagram generator"


authors = [{ "name" = "Romolo Politi", "email" = "romolo.politi@inaf.it" }]
license = "GPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.14, <4.0"
dependencies = [
    "rich-click (>=1.9.7,<2.0.0)",
    "pandas (>=3.0.1,<4.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "python-dateutil (>=2.9.0,<3.0.0)",
]


[project.urls]
Repository = "https://github.com/RomoloPoliti-INAF/Gantty"

[project.scripts]
gantty = "gantty.gantty:main"


[tool.poetry]
packages = [{ include = "gantty", from = "src" }]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
test = ["pytest (>=9.0.2,<10.0.0)", "pytest-cov (>=7.0.0,<8.0.0)"]
devel = ["ruff (>=0.15.4,<0.16.0)"]

[tool.pytest.ini_options]
addopts = [
    "--cov=gantty",
    "--cov-report=term-missing",
    "--cov-fail-under=80",
    "--cov-branch",
]
testpaths = ["tests"]

[tool.coverage.run]
branch = true
omit = [
    "tests/*",
    "src/gantty/__main__.py",
    "src/gantty/__init__.py",
]
